### ISSUE TITLE
Create a class to fetch data from a given api

### ISSUE THREAD

**Issue by tjanowsk** [SL-edi/covid-visualisation#15]
We want to fetch the data of the number of infected/dead/recovered for a given country or worldwide from a third-party api.
We want to have a flexibility to use a different api if needed. To that end, the returned object should have the same format regardless of api contacted, e.g.
```
[
  {
    "date": "2020-08-04T00:00:00Z",
    "infected": 999,
    "dead": 9,
    "recovered": 99 
  },
  ...
]
```

**Comment by AdrianBorg** [comment]
Leaving a comment, so I don't forget to bring it up in the call. 
These are probably thinking too far ahead and could be their own tickets later on if we want them;

- Do we want to make a request for all data when loading the app, then use that data, or have calls for each small request (eg. call for data for uk data today then call for uk data yesterday Vs call for all data at start)?
- Do we want to cache results?
- Should the service use multiple apis (for fallbacks in case one is down) or a single one.

**Comment by tjanowsk** [comment]
My views:
- One call to fetch all data whenever possible, we don't want to DDOS the api
- Initially no caching to keep things simple, we can add caching later as a separate ticket once we decide the strategy
- Single api for now, if we code to an interface we'll be able to add fallbacks later
